### ISSUE TITLE
Agree Project Plan

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#10]
We have discussed two potential routes for the project, both outlined here: https://www.notion.so/General-Plan-a71df95a61e04f7a905360ac89c5eca8

@IreneCMT - I believe the preference is the second option, but if you're able to discuss internally and let me know that would be great as I can then book in the remaining sessions

**Comment by IreneCMT** [comment]
Thanks @thejoefriel As discussed, second option is our preference.

**Comment by thejoefriel** [comment]
Great thanks, for confirming!
