### ISSUE TITLE
Remove double line from read more links

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#117]
__Related issue(s)__

_Add any issues here that may be dependent or must be completed before this issue can be tackled_

__Wireframe link__

_Add link to design here_

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [ ] Add each acceptance criteria as checklist like this...

**Comment by RamyAlshurafa** [comment]
fixed
