### ISSUE TITLE
Sort out Terms of Use and Cookie Policy

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#12]
We need 

- [x] Joe to send typical examples / blurbs to Irene
- [x] Joe to send over cookie tools we'd recommend using so we can see the style
- [ ] Irene to then share Terms of Use and Cookie Policy (if these are documents you host on cloud storage, it will mean we can link to them from the app, but gives you flexibility to then modify if you choose later on)

**Comment by IreneCMT** [comment]
Here's the document [https://drive.google.com/file/d/10HNCtdLfqY8RkVvD8h0Ufxs5yR32R098/view?usp=sharing](url)
