### ISSUE TITLE
Build Wireframes & Design Prototype

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#13]
### Link to wireframes

**Live version**
https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy

**Wireframes from the first round of design**
https://www.figma.com/file/qGu2fzVK5EYqyL5strjP0H/Chiltern-Music-Therapy-(First-prototype)?node-id=0%3A1

### Acceptance
- [ ] Build wireframes
- [ ] Turn wireframes into prototype
- [ ] Make agreed changes following user testing
- [ ] Create design system to be used for development 

### Meeting Recording
Here is a tutorial for how to use Figma as a client: 
https://drive.google.com/file/d/1ZrZr_KtvGuxVoze_zuIcj66fr7wh8wcU/view?usp=sharing

**Comment by thejoefriel** [comment]
@IreneCMT Just to confirm the plan is to have your feedback on the wireframes by Friday so that we can make changes Friday/Monday ahead of User Testing starting

The feedback though can be really spread out with you looking whenever you have time from now until end of Monday and we'll make changes as we go along. 

I will then check in on Friday morning (on Slack) to see where you are with reviewing so we can plan accordingly :)

**Comment by IreneCMT** [comment]
Sounds great!
Looking forward to it.
