### ISSUE TITLE
Client dashboard missing cards

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/chiltern-music-therapy#143]
logged in as client2
- [x] the therapist card is not showing
- [x] no programmes card not showing
![image](https://user-images.githubusercontent.com/34629478/114304640-fe02a180-9adc-11eb-8296-8d6e5b683683.png)

**Comment by thejoefriel** [comment]
I think this has already been fixed but I've pushed a mini fix for this in #151
