### ISSUE TITLE
Add streaming media to relevant places

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#147]
Now we have the streaming feature and aws set up we need to make sure all content cards get and show:

- [x] Player (if audio / video)
- [x] Download link

As part of this issue make sure this has been done in all relevant places:
- [x] Library
- [x] Add programme (review & finish page)
- [x] View programme (client & therapist)

**Comment by RamyAlshurafa** [comment]
done in #142
