### ISSUE TITLE
Sort out Data Agreement

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#16]
Hi @IreneCMT @TimShirra - do you mind looking through and seeing if you're happy with this data agreement? If so I'll share a signed PDF for you to sign also

[Data Sharing Agreement - Yalla and Chiltern Music Therapy.docx](https://github.com/yalla-coop/chiltern-music-therapy/files/6155598/Data.Sharing.Agreement.-.Yalla.and.Chiltern.Music.Therapy.docx)
[Annex data processing terms Yalla.docx](https://github.com/yalla-coop/chiltern-music-therapy/files/6155599/Annex.data.processing.terms.Yalla.docx)

**Comment by thejoefriel** [comment]
Hey @TimShirra did you get a chance to look through this?

**Comment by IreneCMT** [comment]
Hi @thejoefriel Sorry, we forgot to mention this on our meeting last Thursday. @Tim and I had a look at this and had a couple of comments. I'll share the doc with you so we can go through them and complete

**Comment by IreneCMT** [comment]
https://docs.google.com/document/d/1a-5lcTakUD7yB4mQohj_89JNLNK6cSKN6hiR4V2QOPg/edit# 
This is the doc with some of our comments.

**Comment by IreneCMT** [comment]
Anything else you need from us to resolve this one @thejoefriel ?
