### ISSUE TITLE
Define features for upcoming development sprint

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#17]
Following the work in design we now have a strong list of features to match our user journeys :) 

Now we need to prioritise the issues this will provide us:
- A defined scope that serves a minimum deliverables for the upcoming development sprint
- A product backlog of issues ordered in terms of priority that we can tackle in the sprint if we get to and also to serve as the start of a roadmap for the product 

Link to estimations table: https://www.notion.so/Feature-Planning-Time-Estimations-Prioritisation-e6088ca57f844c32a09d8e9961e81d68

**Comment by thejoefriel** [comment]
Hi @IreneCMT thanks for your time earlier! So what I need from you please is:

- [ ] Confirm you are happy with the priority 1s and 2s - these will be the minimum deliverables for the sprint
- [ ] Decide what you want as top level bonus features (from our discussion it's between mobile updates vs feedback)

As discussed the top the total for Estimate 2 days column cannot be higher than 53. Other than that we can move things around to suit your needs.

**Comment by IreneCMT** [comment]
Hi @thejoefriel I reviewed the 1s and 2s deliverables and it looks good, following our conversation about all of these yesterday, there is not much more I would like to add. In regards to the bonus feature, we had some conversations yesterday as something came up that would impact phase 4 (I'll tell you more about this soon, on our next meet up), so although I was inclined to favour messaging at this stage, it might be the case that we leave all the messaging features for a later sprint in the hopes that we can dedicate more time to that and make it a wider scope (from analogue to conventional txt, etc, a bit like we discussed earlier on in our brief). So with that in mind, we can focus on the feedback for now, as a feature that will be helpful for the initial implementation phase and a more accurate evaluation of the platform.

**Comment by thejoefriel** [comment]
OK sounds great @IreneCMT then looks like we're all signed off 🎉 
I will start creating all the issues in Github now, so you can then review acceptance criteria

Thanks for letting me know re the bonus features. I've kept it as is then with the feedback being out priority 3s. I've sent you a note in Slack to see if you want to catch up regarding the latest developments regarding phase 4
