### ISSUE TITLE
Agree Security Testing Plan

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#18]
Hi @IreneCMT @TimShirra 

In our last meeting we discussed that you have a separate budget to carry out external security testing, so the £795 we'd allocated to using third party solution (https://www.intruder.io/) was going to get redistributed to development time.

Are we still happy with this approach?

## Timings
Do you want testing to take place within the project time so we can potentially implement any particular issues that are brought up?

If so, we would need you to set up the third party to test the app between 21st-27th April please. 

Let me know any further thoughts on this :)

**Comment by TimShirra** [comment]
Hi @thejoefriel @IreneCMT,  thanks for the nudge. On the timings, I would say it probably makes sense to line it up as you suggest from Apr 21-27, to give team Yalla time to address any issues of concern. It would also be good for us to get your opinion of the value of the £795 service you had planned originally from Intruder.io.  What service was it (the penetration testing?) - and what does it include? Does it effectively enable you to have access to their service for a few days? have you used them before? Does it include any human input (and if so, did it add any value?)  If you rate them (or their bots) it might be a good option for us to consider.  Thanks 👍

**Comment by thejoefriel** [comment]
Hey @TimShirra just following up to see your thoughts on this?

**Comment by TimShirra** [comment]
Hi @thejoefriel, thanks for the nudge. I have a friend / ex-colleague who's a security testing expert, who may well be willing and able to do this for us, for free or very low cost. @IreneCMT I think is just confirming that we're clear with CAST to use his help. By the by, how many workflows will there be, approx for testing? Thanks and have a nice evening - enjoy the sun!!!

**Comment by thejoefriel** [comment]
Hey @TimShirra thanks for this, this sounds perfect! 
In terms of workflows, I'd say these are probably the core ones we'd want to test?
- Logging in - 3x user types
- Signing up as a therapist (1 x user type)
- Signing up as a client (1 x user type)
- Adding a client (1 x user type)
- Adding a programme / content (1 x user type)
- Viewing a programme / content (2 x user types)
- Sending feedback (2 x user types)

And then there's the admin functionality
- Viewing all content
- Viewing all feedback


Feedback ones are dependent on getting around to those as those features are bonus.
