### ISSUE TITLE
Copy & Basic Design

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#183]
**Bugs**
- [x] 1 - There is a copy error. It says "Please add a therapyBackground of your client's therapy background and goals".  should say "summary" instead of "therapyBackground" 
- [x] 7 - We need to delete the line about videos being password protected please
- [x] 8 - Copy is not right. Should be changed to something more generic without client's initials on it so it can be used widely for all clients. Suggested edit: "Each week, resources will be provided in the ‘Home Programme’ page that support these goals. Current therapy goals are listed by domain area below:"    ALSO: category should come on top of title. In this case "communication" (general) should come on top of "Improve fluency of communication" (specific). 
- [x] 9 - This copy "This will help shape your plan further to reach your goals." to be changed to "This will help us to continue improving our digital resource to support your therapy further" 
- [x] 13 - Add the eye icon to view password when typing. 
- [x] 22 - When entering Phone numbers, system does not validate the number of digits entered. Make it in line with standard UK phone numbers -> 9 to 12 digits long
- [x] 30 - text for goals isn't lining up up properly
- [x] 32 - Phone number not visible on account page. According to Figma , it should have been (?)

**Notion**
https://www.notion.so/3f7ac9a10d93462681

Each number above relates to its number in the notion table

**Comment by fadeomar** [comment]
issue 32 we don't have a phone number field on the client account page according to o Figma https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=802%3A12970

**Comment by thejoefriel** [comment]
Hey @IreneCMT for number 32, actually it's not meant to be on the account page as the client doesn't add their own number (the therapist creates it). Do you want us to add it there though? If so should we also add in the primary contact number too?

**Comment by IreneCMT** [comment]
Yes, @thejoefriel it makes sense. Let's add that to primary contact number too. THanks

**Comment by thejoefriel** [comment]
OK Thanks @IreneCMT - @fadeomar can you sort please?
