### ISSUE TITLE
Documents added to library not then showing in the dropdown to re-use

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#185]
**Bug**
I have added several documents to my library but cannot find them on drop down to re-use

**Notion**
3
https://www.notion.so/3f7ac9a10d934626816587594ce473e7?v=82bea5ffa6cf4b73ab1b716d6a54805f

**Comment by dupreesi** [comment]
this happens because when adding new content to a programme the content only gets stored when hitting save in the end. So in this case the user didn't store the content yet so the dropdown only got old library content.
