### ISSUE TITLE
File type validation - make clearer if that's the reason for file upload not working

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#186]
**Bug**
Not sure if this is BUG or BACKLOG I am trying to upload an audio file I've just recorded, but the app is not recognising this file. Perhaps we need to clarify which extentions this app recognises as audio file for upload. 

**Notion**
4
https://www.notion.so/3f7ac9a10d934626816587594ce473e7?v=82bea5ffa6cf4b73ab1b716d6a54805f

**Comment by dupreesi** [comment]
@thejoefriel maybe its worth adding a helper / popup with the file types allowed for each content type? E.g. Video: mp4, mpeg...
we already have it set up for error handling so could copy across into an info popup / tooltip

**Comment by thejoefriel** [comment]
This is a good idea @dupreesi :)

**Comment by thejoefriel** [comment]
Also @dupreesi what file size limits do we have put in place?

**Comment by dupreesi** [comment]
@thejoefriel yeah we can just make something up I would say. here are sizes and formats:
```
const allowedFileTypesAndSizes = {
  video: {
    types: ['video/mp4'],
    // 2 GB
    maxSize: '2000',
  },
  document: {
    types: [
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    // 20 MB
    maxSize: '20',
  },
  audio: {
    types: ['audio/mpeg', 'audio/wav'],
    // 100 MB
    maxSize: '100',
  },
  image: {
    types: ['image/png', 'image/jpg', 'image/jpeg'],
    // 30 MB
    maxSize: '30',
  },
};
```
