### ISSUE TITLE
Not able to see a video I added

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#187]
**Bug**
I am looking through the home programme I have just created for my client. I am able to see all the files, except for one of the videos. 

**Notion**
5
https://www.notion.so/3f7ac9a10d934626816587594ce473e7?v=82bea5ffa6cf4b73ab1b716d6a54805f

**Comment by dupreesi** [comment]
this relates to #186

**Comment by thejoefriel** [comment]
OK Thanks @dupreesi - so whoever picks up #186 please make sure you check and mark this one as complete once done
