### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#190]
- [x] 16 - When trying to add a video from my device, it loads the file but it doesn't upload in the end. 
- [x] 17 - Similarly to the one above, I can't seem to upload the video I just created to share an update with my therapist
- [ ] 20 - As a therapist I am trying to upload a file. As it's not working I want to go back to the programme I was creating. I can't, and end up loosing what I had started. 
- [x] 24 - Unable to test deletion of video because system did not allow video to be uploaded. Strange

**Notion**
https://www.notion.so/3f7ac9a10d934626816587594ce473e7?v=82bea5ffa6cf4b73ab1b716d6a54805f

**Comment by dupreesi** [comment]
bug no 24 relates to #182 and -> similar to #193
bugs 16, 17, 20 are all related to iOS so we need to make sure to test these scenarios again on an iOS device

**Comment by thejoefriel** [comment]
OK thanks @dupreesi - do you have a iOS device to test? Will you assign yourself those other issues then ?

**Comment by dupreesi** [comment]
@thejoefriel yeah I can test using my iphone so working on it now
