### ISSUE TITLE
Odd looking box in library

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#195]
**Bug**
The remove feature works fine but wanted to point out a strange looking box on the screen in the video link.

**Notion**
28
https://www.notion.so/3f7ac9a10d934626816587594ce473e7?v=82bea5ffa6cf4b73ab1b716d6a54805f

**Comment by fadeomar** [comment]
duplicate #212

**Comment by thejoefriel** [comment]
Closing since this was fixed in other issue #212
