### ISSUE TITLE
Set up files and file structure in the codebase

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#21]
#19 and #20 must be complete first

## Acceptance Criteria
- [x] Set up all the empty files so the structure is clear
- [ ] In each file add comments so it's clear the purpose of this file

**Comment by RamyAlshurafa** [comment]
i added the main file structure without adding all the files, so we add the required files on its issue 
adding comments on each file could be overkill, and the file name should be clear enough to demonstrate its purpose

**Comment by IreneCMT** [comment]
Not sure I understand this one @thejoefriel but I guess it's all the background codebase..
