### ISSUE TITLE
Set Up Database

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#22]
Refer to database schema agreed in #8 

---

### Acceptance Criteria:
- [x] Set up connection
- [x] Build tables
- [x] Add dummy data, suggested dummy approach for now (because programmes are very dependent on the file upload)
    - [x] 1 x client
        - [x] include therapy plan, goals etc
    - [x] 1 x therapist
        - [x] include biography etc
    - [x] 1 x admin
    - [ ] No programmes
    - [ ] No content

**Comment by RamyAlshurafa** [comment]
Agreed with @thejoefriel to add contents and programmes with dummy files
