### ISSUE TITLE
Ensure AWS is secure

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#250]
- [ ] Carry out any remaining tasks required to ensure AWS is secure for file uploads, fetching and storage
- [ ] Ensure what you've done is documented here so we have records

**Comment by dupreesi** [comment]
**S3 bucket configuration updated:** 

1. Permissions
- [ ] Blocked all public access (only users registered on the app can access the bucket)
- [ ] Added specific public policy (Specified allowed object methods (get, put, delete), specified bucket resource, added allowed domains)
- [ ] Specified Cross-origin resource sharing (CORS) config (specified allowed origins, methods and headers)

Added lifecycle rule for temp folder (management section)
- [ ] adds automated object expiration and deletion after 1 day if files are uploaded into /temp folder (all the files that are not part of any programmes or progress-updates
