### ISSUE TITLE
Set up log ins

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#26]
Hi @IreneCMT we please need you to create accounts for a number of essential platforms. This means you have full ownership of the platform as they are all Chiltern accounts. Ideally we get this done before development starts to prevent any unnecessary delays.

Here are the key platforms (there may be more once we agree our analytics approach):

- [x] AWS: https://portal.aws.amazon.com/billing/signup#/start
- [x] Sentry: https://sentry.io/signup/ 
- [x] Sqreen: https://my.sqreen.com/signup?&referrer=aHR0cHM6Ly93d3cuc3FyZWVuLmNvbS9wcmljaW5n
- [x] Heroku: https://signup.heroku.com/login
- [x] Provide us a Gmail account (this will be the email account from which users receive emails so you probably want something like hello@chilternmusictherapy.co.uk or something like that you use for organisation communications) with an app password. For details on how to set up an app password: https://support.google.com/accounts/answer/185833?hl=en

- [x] For each one, once you've set up the account, we need you please to paste the email and password into the protected App Info spreadsheet on issue #1 

**LET US KNOW IF YOU WANT US TO DO IT 👍 **
Setting up these accounts can be a pain! If you provide us a Gmail you want to use for all these logins (e.g. admin@chilternmusictherapy.co.uk) and the password without 2FA set up, we can then set up the rest of the accounts for you, and you will then be able to change the password and enable 2FA at the end of the sprint. 

We would then set up everything up, adding it to the spreadsheet. 

The only bit we would then need you to do would be to log in to AWS to provide the required card details to set up a S3 account.

**Comment by IreneCMT** [comment]
@thejoefriel Quick question, creating that app password will impact how that account is accessed ? Mostly because the generic email address I had in mind is used by a few people, so if I need to change the password that will impact several staff. Otherwise I can look into creating a new account

**Comment by thejoefriel** [comment]
Hi @IreneCMT I don't believe it will change how you log in. It would still be the same password and email address. It's just an extra thing that we use for the API
