### ISSUE TITLE
No input validation/sanitisation on any input fields

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#262]
**Summary**
Any special character can be passed through the input fields such as Name, Search and etc (all of them). See the screenshot below. This means that an attacker can easily inject a malicious payload (injections and XSS attacks). I noticed that this is the issue is persistent across any input fields in the application.

![image](https://user-images.githubusercontent.com/19708921/120184693-2c614b00-c209-11eb-9355-a8dbd6c8a75d.png)

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] The recommendation is to apply the whitelisting approach and only permit characters that are expected in that field (e.g. no need for special characters in the Name field). I would also encourage implementing a central input validation/sanitisation so it can handle all input fields (even those that are going via POST requests).
- [x] The second recommendation here is to implement an output encoding again globally across any input fields. This is to prevent XSS/injection attacks.

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
after looking into the front end validation Ahmed and I agree this is not a real thread, and react is sanitizing /escaping the inputs by default, and the image that been sent be Tim is escaped text and it doesn't run the script

> By default, React DOM escapes any values embedded in JSX before rendering them. Thus it ensures that you can never inject anything that’s not explicitly written in your application. Everything is converted to a string before being rendered. This helps prevent XSS (cross-site-scripting) attacks.

https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks

**Comment by thejoefriel** [comment]
This was agreed with Chiltern so closing
