### ISSUE TITLE
Landscaping for Release 2

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#268]
**PLEASE NOTE, LINKS TO BOARDS TO THEN BE PASTED HERE:**
TBC

**Old landscaping issue with previous work here**
#3 

---

### Summary
With the work in #3 we have a good understanding of the space we're working in. However, with new features we are due to build (refer to #261 ), it is always good to see if there's any further inspiration we want or experiences we should consider. 

### Reminder of what landscaping is
In this issue we are trying to get a better sense of the type of user experience we want to try and build for our users (i.e. the best way for them to interact with our digital tool in order to achieve their needs) and how it might look.

**What other people are doing in this space:**
From our discussions it seems there doesn't appear to much doing what you're wanting to do, but putting here just in case, as this is always useful to ensure we think about:
- What already exists and why it's not fitting the problems we're looking to solve - what are our users needing
- The language other platforms use - what works and what doesn't

**UX / User Experience:**
- User experiences our user personas know and like
- inspiration from platforms that we can use for how users might interact with our own digital platform
- what apps / websites do your clients tend to use?
- what apps / websites do your therapists use?

---

### Please watch below videos and check Acceptance Criteria for further instructions of how to do this exercise

**Please try and comment on this issue with your feedback by Monday 1st March**
- [x] Using the template below, add comments on this issue for each digital tool you feel worth discussing

**Template:**
- App/website name:
- App/website link:
- What is it relevant for: Other Person in Space / UX / Visual
- If possible, the specific part(s) and/or flow(s) you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?

### Video explanations
https://www.loom.com/share/bce88cc1ee3f4aa9833fd8bdd439e94d
https://www.loom.com/share/4a8ee418f94e48b6a6435bd79420a3ac

**Comment by IreneCMT** [comment]
Do we have a date for landscaping already @thejoefriel ? So I can let Katie know
