### ISSUE TITLE
Agree analytics and what we want to track

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#27]
Hi @IreneCMT @TimShirra 

We've discussed tracking engagement but I don't think we've really nailed it down yet. 

**Google Analytics**
- Visitors
- Pageviews
- We could also trick how often pieces of content (e.g. videos, audio, files) are clicked (so that will show content engagement)
- Time spent on the app

**Logrocket**
This doesn't provide "stats" but would allow you to view how the app is being used by live users. We would protect any sensitive information (e.g. passwords, videos) so they aren't recorded, so you're just using it to understand user behaviour. This can be useful, but let me know if you want this as I know privacy is paramount. 

**Native**
Within the app itself we are going to collect the feedback questions

-- 

## Questions for you :) 

- Which platforms do you want us to integrate?
- What statistics beyond the feedback questions do you want to track?

**Comment by IreneCMT** [comment]
@thejoefriel @TimShirra I think the list above is quite good. The "time in the app" one is a bit less representative I think, as people could leave the app open but not necessarily use it.  Is Logrocket like a video of what they did online? I don't see us having the time to explore this, so in my views google analytics sounds the most straightforward

**Comment by thejoefriel** [comment]
Thanks @IreneCMT. Yeah Logrocket would be videos you would watch, so you're right to consider if you have time for this before we set it up. So you thinking we just set up Google Analytics in terms of third party tools?

**Comment by IreneCMT** [comment]
Yes, I think that's ok. And Native for the feedback right?

**Comment by thejoefriel** [comment]
Exactly @IreneCMT . 

@TimShirra you happy from this as well?

**Comment by TimShirra** [comment]
Yes, if Irene is happy, I am too. I guess where use of Log Rocket is concerned, it could come in handy where, if it turns out from analysis from Google Analytics  that people are exhibiting unexpected behaviour (visiting pages less than you'd expect), or getting 'stuck' for longer than expected on a particular 'transient page' then you might want to use a video tool to help you work out what's happening.

**Comment by IreneCMT** [comment]
I am just slightly concerned about video tools to track users, I think we might need consents to do this. Let's leave it with Google Analytics and Native for now, and leave Logrocket within recommendations for the future, can we make sure we keep a record of this on recommendations docs @thejoefriel ?
