### ISSUE TITLE
Admin Sign Up (BACK)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#274]
__Related issue(s)__
#273 

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Set up backend to store organisation after first sign up page
- [x] Add new fields to databases 
    - [x] unique url
    - [x] status - active, awaiting_approval, deactivated
    - [x] visited_since_approval - boolean (this is there so we determine whether to show them the Approved page) 
- [x] Create update controller and query to store logo and update url (if changed) from the second page 
- [x] Back end validation to stop two accounts with same organisation name from signing up -> Message "Organisation with that name already exists"

**Comment by fadeomar** [comment]
- [ ] The unique url to show is the organisation name with spaces turned into hyphens (so Yalla Cooperative becomes yalla-cooperative) (from issue  #273)
