### ISSUE TITLE
Set up Twilio + Message Automation

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#277]
**Summary**
We need to set up Twilio to send text messages for the following scenarios
- New programme
- Response from Therapist
- Updated programme

These are all scenarios already covered by emails, so it would be sending a text message as well if the user has opted to be kept up to date by message 

**Links**
Refer to Twilio documentation here: https://www.twilio.com/docs/sms/quickstart/node

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create a Twilio account
    - [x] Use the common email we've used for all the accounts - #1 
    - [x] Ensure we get a UK Twilio phone number when setting up the account 
- [x] Connect with our backend setting up a similar service to emails (as the events e.g. new programme that trigger an email will be what trigger a text message as well) 
- [x] Add new field to database
    - [x] phone_updates: BOOLEAN
- [x] Ensure the following scenarios trigger the message service (if phone_updates is TRUE)
   - New programme
   - Response from Therapist
   - Updated programme  
- [x] Send text message to mobile number 
- [x] Write details here as comment on how to manage the Twilio account in case we need to add further messages in future

---

### What we need from CMT

Hey @IreneCMT can you please let us know what you want the content of each of these text messages to be?
   - New programme
   - Response from Therapist
   - Updated programme

**Comment by RamyAlshurafa** [comment]
Steps for adding new messages in twilio:
- add new function that returns the message text here `server/services/sms-notifications/templates.js`
- declare new key in the keys, and associate that key to the function created in step 1`server/services/sms-notifications/template-keys.js` 
- in the events service import the sendSMS function and invoke it with the proper key if the user has enabled SMS notifications 
```js
    if (progressUpdate.client.contactByPhone) {
      await sendSMS(sendSMS.KEYS.CLIENT_THERAPIST_RESPOND_TO_PROGRESS_UPDATE, {
        to: progressUpdate.client.contactNumber,
      });
    }
```

**Comment by thejoefriel** [comment]
Hey @IreneCMT sorry but we still haven't received what you want the content of each of these text messages to be? Can you please send across tomorrow at some point.

**Comment by IreneCMT** [comment]
Hi @thejoefriel and @RamyAlshurafa. My apologies, I thought I had sent this already as I wrote it a while ago. Please see link below. (It also includes the emails text as there a few amends due to the change of name to DUET). 
https://docs.google.com/document/d/1Tl9MtcBSdg39k-yGmgGEJoOSHJaZp8dkUEqenWae7yQ/edit?usp=sharing
