### ISSUE TITLE
Create Dashboard + How It Works page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#279]
**__Wireframe link__**
1. https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=2971%3A28450
2. https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=2969%3A26315

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create pages in line with wireframes
- [x] If the Icon and Text component isn't a common component already then create it as a common component 

---

### What we need from CMT

Hey @IreneCMT can you provide us the links for when the user clicks to view video or read the user guides please? We'd recommend putting these somewhere where you could update them if you like without the link changing (e.g. on a page of the CMT website or on a Notion page)

**Comment by IreneCMT** [comment]
Hi @thejoefriel Here's the link to the client userguide. There is no video for clients at the moment 
https://drive.google.com/file/d/1RhvgDHkTnh8T2OXcsNhjzgJCIbtO2jF2/view?usp=sharing

**Comment by IreneCMT** [comment]
These are the lnks to therapists training video and user guides
Training: https://drive.google.com/file/d/1jZjiEVlEbeoVi7c4KR0x30vsJ78cp7vj/view?usp=sharing
Userguide: https://drive.google.com/file/d/188E8zOS6nBUfZz9Tl91ThUmbTh7sr2QK/view?usp=sharing
