### ISSUE TITLE
Ensure Therapist has to understand how it works 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#280]
**Summary**
We want to ensure therapists always understand how the platform works so we need to ensure they have watched the information video 

**Wireframes**
1. https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=2971%3A27608
2. https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=2971%3A27592

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Add new wireframe
- [x] Add new field to db
    - [x] watched_tutorial = BOOLEAN
- [x] Add new api call to update to true if use ticked and clicks confirm 
- [x] If therapist has no clients yet and clicks to add a client, send a api call to check if they have watched_tutorial
    - [x] If false show this modal https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=2971%3A27592
    - [x] On watch video then redirect to this page: https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=2971%3A27667

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel @IreneCMT 
can you provide the video's link for this, please

**Comment by IreneCMT** [comment]
@RamyAlshurafa Hi Ramy, here the links to both the training video and the therapist user guide. 
Duet Therapist User Guide: https://drive.google.com/file/d/188E8zOS6nBUfZz9Tl91ThUmbTh7sr2QK/view?usp=sharing
Duet Therapist Training: https://drive.google.com/file/d/1jZjiEVlEbeoVi7c4KR0x30vsJ78cp7vj/view?usp=sharing
