### ISSUE TITLE
Build boards of UX and Visual inspiration

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#3]
**PLEASE NOTE, LINKS TO BOARDS TO THEN BE PASTED HERE:**
https://www.notion.so/Landscaping-8ccb38deecad47f6a3ae064447f0b714

**For different views select the view next to "Inspiration"**

## Meeting Video
Here is the video of the landscaping session:
https://drive.google.com/file/d/11MohIZGgHFT4WZZPvPIGwAbyH74DPJjK/view?usp=sharing

---

### Summary
In this issue we are trying to get a better sense of the type of user experience we want to try and build for our users (i.e. the best way for them to interact with our digital tool in order to achieve their needs) and how it might look.

**What other people are doing in this space:**
From our discussions it seems there doesn't appear to much doing what you're wanting to do, but putting here just in case, as this is always useful to ensure we think about:
- What already exists and why it's not fitting the problems we're looking to solve - what are our users needing
- The language other platforms use - what works and what doesn't

**UX / User Experience:**
- User experiences our user personas know and like
- inspiration from platforms that we can use for how users might interact with our own digital platform
- what apps / websites do your clients tend to use?
- what apps / websites do your therapists use?

**Visual:**
- What visual language do you think suits the user personas in terms of typography, colour and graphics/illustrations. What would be attractive to them?
- What is the visual identity or the app? Are there Chiltern Music Therapy brand guidelines for us to work under?

**Accessibility**
This has an important part in our design. We need to agree what level of accessibility, following agreed standards. Our assumption would be AA as a minimum but aiming for AAA. 
Details here: https://www.w3.org/WAI/WCAG2AAA-Conformance

---

### Please watch below videos and check Acceptance Criteria for further instructions of how to do this exercise

**Please try and comment on this issue with your feedback by Monday 1st March**
- [x] Using the template below, add comments on this issue for each digital tool you feel worth discussing

**Template:**
- App/website name:
- App/website link:
- What is it relevant for: Other Person in Space / UX / Visual
- If possible, the specific part(s) and/or flow(s) you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?

- [x] List links / documents for any brand guidelines we need to follow

- [x] Please let us know in a comment your views on the level of accessibility 

### Video explanations
https://www.loom.com/share/bce88cc1ee3f4aa9833fd8bdd439e94d
https://www.loom.com/share/4a8ee418f94e48b6a6435bd79420a3ac

**Comment by thejoefriel** [comment]
Two platforms already mentioned are:
- Moddle (Tavistock Moodle)
- Noise solutions

What is about these @IreneCMT that you think are of interest?

**Comment by IreneCMT** [comment]
@thejoefriel I think the link to this websites is mostly the format of accessing digital content. I haven't had a personal experience of them so I can't give a huge amount of information. Noise Solutions is basically a platform for music teachers to provide personalised classes and content for their students, in an interactive way, as students can also upload their videos, etc. 
Links are; https://moodle.org/ (the Tavistock portal is basically the use of moodle with an organisational design, logos colours, and content). https://www.noisesolution.org/s/

**Comment by IreneCMT** [comment]
App/website name: Chiltern Music Therapy

App/website link: www.chilternmusictherapy.co.uk

What is it relevant for: Other Person in Space / UX / Visual

If possible, the specific part(s) and/or flow(s) you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?
This is an obvious choice, but I think it is good to have this as starting point of reference of visuals, as we are aiming to maintain a flow with our general branding style. (I am trying to get you a branding guidance book so hopefully I can provide you with more specifics on font/colours, etc)

**Comment by IreneCMT** [comment]
App/website name: Splinx

App/website link: https://splinx.co.uk/

What is it relevant for: Other Person in Space / UX / Visual

If possible, the specific part(s) and/or flow(s) you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind? 
Splinx has a similar style to CMT in regards to visuals, with general white backgrounds and colourful logo. We like the modern and rather simple visuals of it.

**Comment by IreneCMT** [comment]
App/website name: MindHarp

App/website link: https://mindharp.world/

What is it relevant for:  Visual

If possible, the specific part(s) and/or flow(s) you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?
A completely different app to what we are trying to achieve, but again, this is an app we work a lot with in clinical work, and visually it aligns with our style I believe

**Comment by IreneCMT** [comment]
Hi @jema28  Thanks for the videos you created for this issue. I have added a few ideas, mostly around visual inspiration that I hope help for landscaping. It is harder than I thought to find examples for this, but I'll keep digging and thinking and adding into this issue as I come up with more ideas.

**Comment by jema28** [comment]
Hi @IreneCMT, thanks a lot for these - going through them today. Yeh, I've been finding it a bit tricky too so no worries if you can't find many more.

If you're looking for more sites to have a look through though https://dribbble.com/ is great and https://www.pinterest.co.uk/ too in some cases. 

This notion doc includes the things I've found so far https://www.notion.so/Landscaping-8ccb38deecad47f6a3ae064447f0b714. If you look at the Gallery view, you'll see some of them have images:

<img width="2066" alt="Screenshot 2021-03-02 at 09 55 48" src="https://user-images.githubusercontent.com/25960351/109631063-85074600-7b3d-11eb-9b36-653d65c5cdd3.png">

Hope that's helpful!

**Comment by jema28** [comment]
Hi @IreneCMT, I'm not able to see the things you mentioned on Noise Solutions without a login, do you have one you can DM me on slack?

**Comment by IreneCMT** [comment]
Hi Jem. 
Unfortunately we dont have log in to this platform. We’ve seen it on demos in the past


Irene Lo Coco
Music Therapist
Chiltern Music Therapy

Music Therapist
HCPC registration AS16187

M		07512 537819
T		01442 780541
E		irene@chilternmusictherapy.co.uk
W		www.chilternmusictherapy.co.uk
  
Chiltern Music Therapy Community Interest Company No. 7702358
Registered address: Irfon House, Stones Courtyard, High Street, Chesham, Buckinghamshire, HP5 1DE
  
This e-mail and any attachments are confidential and intended solely for the addressee. If you are not the addressee or have received this e-mail in error, please notify the sender immediately, delete it from your system and do not copy, disclose or otherwise act upon any part of this e-mail or its attachments.

**Comment by jema28** [comment]
No problem @IreneCMT, thanks

**Comment by thejoefriel** [comment]
To confirm we're using AA as a minimum for accessibility
