### ISSUE TITLE
Provide domain

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#302]
Hi @IreneCMT  !

As we approach deployment time we need to get the domain. Just outlining the tasks so we've got them all. 

- [x] Get your domain set up with whoever handles your hosting
- [x] Let us know the domain
- [x] Connect us with your digital team (if applicable) so we can send them the heroku code for them to link up the CNAME record OR provide us with log in details to your hosting provider so we can update it ourselves

After that it should be all linked up!

**Comment by IreneCMT** [comment]
Hi @thejoefriel I should be able to provide this early next week. Hope that's ok

**Comment by IreneCMT** [comment]
@thejoefriel the web people are asking the following: 
I can order these two domains for you at those cost prices. Do you have somewhere for them to point to or are you merely reserving them at this stage?"
