### ISSUE TITLE
Refactor website following AXE scanning on each page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#304]
We need to improve the overall accessibility of the tool. So we're doing a self-audit via Axe

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Install Axe dev tools
- [x] Scan each page of the app (use the nav routes to tick everything off and make sure you go through all flows) 
- [x] Fix each Critical and Serious risks **(not moderate or minor)** 
- [x] Add a comment here of the risks for each page so we can keep a log of the risks identified (doesn't need huge details, just copy and paste the title so we have a general reference)

**Comment by Israa91** [comment]
##### Fix navbar link so that it have discernible text
###### error --> ``` Links must have discernible text ```

**Comment by Israa91** [comment]
##### Fix  go back button to have discernible text
###### error --> ``` Button must have discernible text ```

**Comment by Israa91** [comment]
##### Fix page not found color so that it have sufficient contrast ---> used "gray8" color instead "gray" color
###### error --> color should have sufficient contrast

**Comment by Israa91** [comment]
##### fix error color ---> used pink = '#CA3F93' instead of pink = '#CB4394' , so that text have sufficient contrast
###### error --> Text should have sufficient contrast

**Comment by Israa91** [comment]
##### Fix info button in password input ,so that it have arai label 
###### error --> Buttons must have discernible text

**Comment by Israa91** [comment]
##### Fix color in route /contact-therapistb ---> used "gray8" instead of "gray7"
###### error --> Elements must have sufficient color contrast

**Comment by Israa91** [comment]
##### Fix aria props in dropdown component
###### error
###### Required ARIA attribute not present: aria-expanded  
###### ARIA attributes must conform to valid values

**Comment by Israa91** [comment]
##### I found that color "gray7 " have insufficient contrast with the white background , so I changed it

**Comment by Israa91** [comment]
## Not Complete
##### There are two warnings ,I still cann't solve them
- [ ] ARIA dialog and alertdialog nodes should have an accessible name : this warning appears every time modal is opened
- [ ] ARIA dialog and alertdialog nodes should have an accessible name : this warning appear when there is a dropdown list and no choice is chosen ,once any choice is chosen the warning disappear
