### ISSUE TITLE
Increase font size dynamically

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#306]
__Related issue(s)__

#305 needs to be created first so you have the button in the navbar

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

I'm not 100% sure on best approach of this so I've laid out what I think is the simplest way to sort this 

- [ ] Create font-sizes constants file
    - [ ] Create the object so each font-size we use (refer to Typorgraphy component) has a reg and large e.g. ```{ 16px: { reg: '16px', large: '19px' } }``` 
    - [ ] For large work on 20% increase rounded to nearest number (e.g. so 24px would be 29px)
- [ ] Update the typography component
    - [ ] pass down prop of reg or large 
    - [ ] everything uses the font-sizes constants and gets the right value based on being reg or large 
- [x] Search reset of front end style sheets for any places where font size has been put in separate to Typography component and ensure it does the same check 
- [x] Create function so when user clicks A+ button in navigation it automatically increases all the font sizes. This could be react context perhaps or potentially local storage (so if the user goes away and comes back their preference is automatically saved) 
- [x] If clicked on mobile menu then automatically close the menu after being clicked

**Comment by Israa91** [comment]
#### Hint
I used another way than what written in this issue,so I didn't check all the checkboxes.
