### ISSUE TITLE
Use pub-sub to handle therapists deactivations for clients login

### ISSUE THREAD

**Issue by AdhamHaisami** [yalla-coop/chiltern-music-therapy#307]
__Related issue(s)__

_Add any issues here that may be dependent or must be completed before this issue can be tackled_

__Wireframe link__

_Add link to design here_

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [ ] Add new state in client user 
- [ ] update this state whenever the therapist is activated/deactivated to prevent the client from login if their therapist is deactivated 
- [x] Remove commented code from /server/modules/user/use-cases/login "Lines between 40-50"

**Comment by RamyAlshurafa** [comment]
closing this as the logic has been changed in #321
