### ISSUE TITLE
Updating logins

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#365]
Hey @IreneCMT I realised there are still a few things we need to sort out so you have full management of the platform. Can you please:

- [x] Create email for super admin and send to us
- [x] Change password for your admin (current log in is in the #1 issue) - you can do this in the account settings when you log in
- [x] Update the password in the admin spreadsheet if you would like it stored there OR delete the password and add a note that this is not there for security purposes but to contact you if any issues 

Thanks!

Joe

**Comment by IreneCMT** [comment]
Hi @thejoefriel can I have a link for the admin spreadsheet please? Thanks

**Comment by IreneCMT** [comment]
@thejoefriel 
Super Admin email address and password: 
Account: duet@chilternmusictherapy.co.uk
password: h5uF7=4&
