### ISSUE TITLE
Update Twilio account

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#367]
Now we know everything is working @IreneCMT , we need to move Twilio away from the free version. Do you mind logging into your Twilio account (log ins in #1 ) and clicking to upgrade it  please? You'll also need to add your card details. 

If any problems let me know!

**Comment by IreneCMT** [comment]
Thanks @thejoefriel We'll probably do this from January, would that be ok?

**Comment by thejoefriel** [comment]
Hey @IreneCMT the only problem though is the option to say you want to be updated for text messages is now on the app?

**Comment by IreneCMT** [comment]
@thejoefriel Ok, upgraded now. I have top up a fix amount, but I'm still unsure what should we expect in terms of monthly/annual costs for Twilio. Any ideas @thejoefriel ?

**Comment by thejoefriel** [comment]
Hey @IreneCMT just to confirm I've added this to the ongoing costings here https://www.notion.so/Ongoing-costs-6c204ca8e7ff4d9d946d7d550e85b332
