### ISSUE TITLE
Create Cards component

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#41]
__Related issue(s)__

Some of the cards requires components like #37 and #39 but aren't essential as content would just be fed into cards as children most likely

__Wireframe link__

https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=469%3A30652

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

**Note: If you see a solid green border around any of the cards ignore this. This is a bug on Figma not part of the design. Always inspect the component and look at the CSS to be sure of styling**

- [x] Basic card
    - Simply includes information and possibly links 
- [x] Link card
    - Is basically a link that will take the user to another page
    - You can see there are a few variations on these
- [x] Expandable card
    - These cards when click should expand and then the content in the card should change
    - Ensure prop is include to close card again (this would happen if in the parent component there are more than one card and another card gets clicked)
- [x] Info card
- [x] Make sure to use common margin component in styling #32 
- [x] Add to storybook

**Comment by dupreesi** [comment]
for the person working on this: for the add content (video, doc, audio) card please also check related page /pages/Therapist/CreateProgram/AddSingleContent. 
The card could / should be used here
