### ISSUE TITLE
Create Link component

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#43]
**Related issue**
You need the icon component #37 

__Wireframe link__

https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=1378%3A22097

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create link component
- [x] Make sure to force the url to wrap (in case it's extra long) to stay contained in the parent div
- [x] When user clicks copy, copy the url to the browser and show Copied 
- [x] Use common margin component #32

**Comment by IreneCMT** [comment]
Not sure I understand what this one is for? @thejoefriel
