### ISSUE TITLE
Sign Up: I can create a therapist account choosing my email and password

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#44]
__Wireframe link__

https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=1206%3A27574

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Front end design in line with wireframes
- [x] Form validation
        - All fields required
        - Make sure its a valid email type
        - "Password must contain a minimum of 8 characters, one capital letter, one lowercase letter, one number and one non-alphanumeric character (e.g. ! ? >)"
- [x] Links open up new tab to the conditions
- [x] Set up api call
- [x] Check to make sure account with email address doesn't already exist
- [x] Add user in database
- [x] Handle error messaging (wireframe shows how errors are shown)

---

## Needed from Chiltern

Hi @IreneCMT , do you mind sharing links to your Terms of Use and Privacy Policy please?
We'd recommend putting them as google docs with view only and then that way if you want to change them in future you can 

Let me know if you need any help putting these together. There's examples from Tempo here that you could use as a basis: https://tempotimecredits.org/sign-up

**Comment by IreneCMT** [comment]
Hi @thejoefriel Here's the privacy statement https://docs.google.com/document/d/1KXb2GyC0H7NhQKFdrTQQNWjChFso0WwQ/edit

**Comment by RamyAlshurafa** [comment]
Hi @IreneCMT 
can you share a public link for the privacy, it should be view only access level
i got this when i tried to open it
![image](https://user-images.githubusercontent.com/34629478/113298790-dc4b3280-9304-11eb-9d18-dc8cd738db70.png)
