### ISSUE TITLE
Set up email integration

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#49]
This issue is to set up the nodemailer email integration to send automated emails and the initial email templates

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Set up nodemailer integration and email service
- [ ] Connect with the CMT email account provided in #1 
- [x] Add email templates (that will be triggered to go out when the relevant pages are completed)

---

### What we need from Chiltern

Hi @IreneCMT we need the copy for the emails that will be sent out please. For each one please we need:
- Title
- Email copy

Here are the emails we need to cover please:
- [x] Inviting client to sign up
- [x] Notifying a client that their therapist has sent them a new programme
- [x] Notifying a client that their therapist has edited one of their programmes
- [x] Notifying a therapist that their client has sent an update on how they're getting on with the programme
- [x] Sending a client the response from their therapist
- [x] Notifying a therapist that their client has completed a programme and provided feedback (Irene do we want this one, I wasn't sure?)
- [ ] Notifying a therapist that their client has deleted their account

Let me know if there's any others I've missed! 

Here's an example for if the user has chosen to reset their password (feel free to let me know if you want this to change. For example, if there's a number we should provide if they need to notify someone ):
- Title: Reset your Chiltern Music Therapy password
- Text: 
Hi [First name]

We've received your request to reset your Chiltern Music Therapy password. Click this link to set-up your new password: [Link]

Didn't request a password reset?
If you didn't ask for your password to be reset please get in touch with Chiltern Music Therapy.

**Comment by IreneCMT** [comment]
@thejoefriel slightly worried about this one 
"Notifying a therapist that their client has deleted their account" , as this seems to have come up lately and I don't think we want to give clients the feature to delete de account independently

**Comment by IreneCMT** [comment]
Adding the content here: https://docs.google.com/document/d/1Tl9MtcBSdg39k-yGmgGEJoOSHJaZp8dkUEqenWae7yQ/edit
