### ISSUE TITLE
I can view individual home programme 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#60]
__Wireframe link__

https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=470%3A422

Also expanded views of the cards (examples)
https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=695%3A14
https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=695%3A43

If update / feedback provided
https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=699%3A14

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create pages in line with wireframes
- [x] Api call and db query to get the programme description and all the content for that programme
- [x] Check if update for this programme already stored in db. If so, then show success message (refer to update / feedback provided wireframe above). And if message from therapist then show that too
- [x] Check if feedback provided for this programme already stored in db, If so then show success message (refer to update / feedback provided wireframe above)
- [x] Use card component #41 
- [ ] Use media streaming component #35 
- [x] Even if able to stream, show the file as a download link
- [x] If an external link (i.e. the therapist pasted an external video link rather than uploading) then show link which opens to new tab when clicked
- [ ] Only one content card should be expanded at once so clicking any other content card should close any other
- [ ] Ensure ref is used on the card clicked (to expand or not) so it still stays top of screen even with the content expanding so the user doesn't lose their place on the page

**Comment by thejoefriel** [comment]
The whole automatically closing cards so only one is open in action actually made for a really bad UX. Even if you scrolled to the card, it meant there was lots of movement of the screen which was disorientating. 

So I've implemented a simpler approach which adds a cross at the end of each card. This allows the user to open as many cards as they like and also close them, giving them more freedom and ensuring their position on the screen isn't adversely affected. 

An example here: https://www.loom.com/share/b8e40c6f87b84c99a2255b98d4aeb6b1

@IreneCMT let me know if that sounds and looks ok :)

**Comment by IreneCMT** [comment]
Yes, @thejoefriel looks great
