### ISSUE TITLE
I can add a client (FRONT)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#72]
__Related issue(s)__

_Add any issues here that may be dependent or must be completed before this issue can be tackled_

**Notes**
This includes all the add new client pages and generating a unique link

__Wireframe link__

https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=707%3A0
(and all add new client pages to the right of this)

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Validation
    - [x] First page 
        - [x] All fields required
    - [x] Second page
        - [x] Email required
        - [x] Valid email type
    - [x] Third page
        - [x] At least one goal required
        - [x] Therapy background required
    - [x] Fourth page
        - [x] Must either enter a biography or selected to use main biography
    - [x] Fifth page
        - [x] all fields required
- [x] For the examples (background and goals) these are to use the exact copy provided in the wireframes. This is hardcoded (i.e. not something that currently can be edited anywhere else) 👍 
- [x] To confirm, the image on Add New Client is of the therapist and is **not** an upload feature
- [x] On success show success page and invite link 
- [x] Hard refresh (i.e. hitting refresh in the browser) will mean the user loses the content they entered
- [x] Show error messages if any 

--- 

### Needed from Chiltern

Hi @IreneCMT is there a list of therapy goal categories that we would give the therapist to select from? If so could you send across please?

**Comment by IreneCMT** [comment]
Hi @thejoefriel I have added the categories on figma a while ago. I'll look into it and add them here.

**Comment by IreneCMT** [comment]
Communication and Language
Behaviour and Emotional expression
Physical presentation / Motor skills
Cognition
