### ISSUE TITLE
Delete User Account

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#76]
__Wireframe link__

https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=701%3A779

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create pages in line with wireframes
- [x] Show success message on succesful delete
   - [x] OK would then take them to log in page
   - [x] Also clear the log in token
- [x] Remove all user data following the approach agreed in comments below 
- [x] Trigger email to notify therapist

---

## Needed from Chiltern

Hi @IreneCMT @TimShirra quick question on this. Do you want us to complete remove the user (so delete all programmes everything) or delete only anything that is sensitive to that user?

So the two options could be:

**Option 1**
- Delete everything from user, including any programmes and feedback

**Option 2**
- Delete any personal information about the user
- Delete any content only linked to that user
- BUT keep the programmes and feedback

**Comment by IreneCMT** [comment]
Hi @thejoefriel We need to keep some records of the interaction for safeguarding reasons up to 7 years so we'll need to at least go with option 2. Having said that, from the wireframe it looks like it's the client deleting the account, and I don't think that is an option we discussed. It would be the therapist deleting the account once the client has been discharged or the digital therapy is stopped.

**Comment by thejoefriel** [comment]
Hi @IreneCMT sorry I missed this. So you have to give the client the right to delete their account for GDPR purposes. Sorry if any misunderstanding on this. 

We haven't given the therapist the ability to delete clients in this iteration. Let me know if you need to talk through this

**Comment by thejoefriel** [comment]
The other option @IreneCMT is that we put the Delete Client Account button at the bottom of the client page on the Therapist view and then for the client we just tell them to contact their therapist to delete their account. 
You free to jump on a call to discuss?

**Comment by IreneCMT** [comment]
@thejoefriel This sounds like a good compromise to this element, for the client to contact therapist to delete account. If that complies with GDPR requirements then I am happy with that option

**Comment by thejoefriel** [comment]
Hi @IreneCMT so following our conversation on Whereby just now we're going to keep it as is that the client can delete their account (via the wireframe flow) and then in training for therapists, it will be made clear to them that when they discharge the client they should tell them how they can delete their account. 

To confirm it will follow option 2 outlined above in terms of what is deleted. 

@RamyAlshurafa there's one extra thing on this:
- [ ] Deleted members when shown on Therapist view (dashboard or feedback) will be shown as 'Discharged User'

**Comment by IreneCMT** [comment]
Perfect. Thanks Joe and Ramy
