### ISSUE TITLE
Technical Planning

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#8]
### Summary

This issue is to capture the ongoing discussions around everything related to the technical build and anything our tech team needs to look into / research / consider. 

Full sign off on database architecture and tech stack would be later following design thinking and initial user testing. This will be included in separate issues that this will link to.

**Comment by TimShirra** [comment]
Thanks, Joe, Simon, Ramy, Irene
Very good session this morning, thanks for all your research and hard
thinking on these matters.
You'll be pleased to hear, I don't have any actions to add! 😎
Best wishes,
Tim


Mobile : +44 (0) 7769 743 902

**Comment by thejoefriel** [comment]
Haha thanks @TimShirra 😄

**Comment by thejoefriel** [comment]
Hi @TimShirra @IreneCMT , here is the review document we went through yesterday outlining the entire technical approach and also the database schema:
https://www.notion.so/Tech-Stack-External-Services-Deployment-Recommendation-4ded8db6cbfa40cc8cbf69a8ec50e97c

Please feel free to go through and let me know if you want anything changed! Ideally though for anything major like technologies and database schema we need to finalise by end of tomorrow as we're looking to set up the codebase this week. 

Thanks! :)

**Comment by TimShirra** [comment]
Hi @thejoefriel @IreneCMT Thanks, that all looks clear to me as things stand. The only other thought that occurred to me, looking at the Database schema, was that, to align any future cross-reporting and data consolidation between the Music Therapy app data and Chiltern's main Salesforce client data, it would be good to consider capturing a user's name in in a format to line up with that structure in Salesforce, which seems to be a Salesforce 'formula field' in the format of "FirstName" + " " + "LastName".  Thanks 👍

**Comment by IreneCMT** [comment]
Sounds good to me
